language: perl

perl:
    - "5.22"
    - "5.16"

jdk:
    - oraclejdk8

addons:
    apt:
        packages:
            - oracle-java8-installer

env:
    global:
        - RELEASE_TESTS=1
        - KAFKA_BASE_DIR="${TRAVIS_BUILD_DIR}/kafka"

cache:
    directories:
        - vendor

before_install:
    - ./install_kafka.sh

